name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.9' # sesuaikan dengan versi Go kamu

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy
          
    - name: Create prod.yaml from GitHub secrets
      run: |
        mkdir -p variables
        echo "database:" > variables/prod.yaml
        echo "  postgreSql:" >> variables/prod.yaml
        echo "    driver: postgresql" >> variables/prod.yaml
        echo "    username: ${{ secrets.DB_USERNAME }}" >> variables/prod.yaml
        echo "    password: ${{ secrets.DB_PASSWORD }}" >> variables/prod.yaml
        echo "    host: ${{ secrets.DB_HOST }}" >> variables/prod.yaml
        echo "    port: ${{ secrets.DB_PORT }}" >> variables/prod.yaml
        echo "    name: ${{ secrets.DB_NAME }}" >> variables/prod.yaml
        echo "    schema: ${{ secrets.DB_SCHEMA }}" >> variables/prod.yaml

    - name: Skip test (belum ada)
      run: echo "No tests yet"

    - name: Build binary
      run: go build -v ./...
